use serde::{Deserialize, Serialize};

/// BACnet standard property identifiers (ASHRAE 135-2020 §23.5).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PropertyIdentifier {
    // Common required
    ObjectIdentifier,
    ObjectName,
    ObjectType,
    Description,
    ProfileName,

    // Analog / Value objects
    PresentValue,
    StatusFlags,
    EventState,
    Reliability,
    OutOfService,
    Units,
    MinPresentValue,
    MaxPresentValue,
    CovIncrement,
    TimeDelay,
    NotificationClass,
    HighLimit,
    LowLimit,
    Deadband,
    LimitEnable,
    EventEnable,
    AckedTransitions,
    PriorityArray,
    RelinquishDefault,

    // Device object
    SystemStatus,
    VendorName,
    VendorIdentifier,
    ModelName,
    FirmwareRevision,
    ApplicationSoftwareVersion,
    ProtocolVersion,
    ProtocolRevision,
    ProtocolServicesSupported,
    ProtocolObjectTypesSupported,
    ObjectList,
    MaxApduLengthAccepted,
    SegmentationSupported,
    ApduTimeout,
    NumberOfApduRetries,
    MaxMaster,
    MaxInfoFrames,
    DatabaseRevision,

    // Multi-state objects
    NumberOfStates,
    StateText,

    // Special read specifiers
    All,
    Required,
    Optional,

    /// Catch-all for vendor-specific or future properties.
    Unknown(u32),
}

impl PropertyIdentifier {
    pub fn from_u32(v: u32) -> Self {
        match v {
            75 => Self::ObjectIdentifier,
            77 => Self::ObjectName,
            79 => Self::ObjectType,
            28 => Self::Description,
            168 => Self::ProfileName,
            85 => Self::PresentValue,
            111 => Self::StatusFlags,
            36 => Self::EventState,
            103 => Self::Reliability,
            81 => Self::OutOfService,
            117 => Self::Units,
            69 => Self::MinPresentValue,
            65 => Self::MaxPresentValue,
            22 => Self::CovIncrement,
            113 => Self::TimeDelay,
            17 => Self::NotificationClass,
            45 => Self::HighLimit,
            59 => Self::LowLimit,
            25 => Self::Deadband,
            52 => Self::LimitEnable,
            35 => Self::EventEnable,
            0 => Self::AckedTransitions,
            87 => Self::PriorityArray,
            104 => Self::RelinquishDefault,
            74 => Self::NumberOfStates,
            110 => Self::StateText,
            112 => Self::SystemStatus,
            121 => Self::VendorName,
            120 => Self::VendorIdentifier,
            70 => Self::ModelName,
            44 => Self::FirmwareRevision,
            12 => Self::ApplicationSoftwareVersion,
            98 => Self::ProtocolVersion,
            139 => Self::ProtocolRevision,
            97 => Self::ProtocolServicesSupported,
            96 => Self::ProtocolObjectTypesSupported,
            76 => Self::ObjectList,
            62 => Self::MaxApduLengthAccepted,
            107 => Self::SegmentationSupported,
            11 => Self::ApduTimeout,
            73 => Self::NumberOfApduRetries,
            64 => Self::MaxMaster,
            63 => Self::MaxInfoFrames,
            155 => Self::DatabaseRevision,
            8 => Self::All,
            105 => Self::Required,
            80 => Self::Optional,
            other => Self::Unknown(other),
        }
    }

    pub fn to_u32(self) -> u32 {
        match self {
            Self::ObjectIdentifier => 75,
            Self::ObjectName => 77,
            Self::ObjectType => 79,
            Self::Description => 28,
            Self::ProfileName => 168,
            Self::PresentValue => 85,
            Self::StatusFlags => 111,
            Self::EventState => 36,
            Self::Reliability => 103,
            Self::OutOfService => 81,
            Self::Units => 117,
            Self::MinPresentValue => 69,
            Self::MaxPresentValue => 65,
            Self::CovIncrement => 22,
            Self::TimeDelay => 113,
            Self::NotificationClass => 17,
            Self::HighLimit => 45,
            Self::LowLimit => 59,
            Self::Deadband => 25,
            Self::LimitEnable => 52,
            Self::EventEnable => 35,
            Self::AckedTransitions => 0,
            Self::PriorityArray => 87,
            Self::RelinquishDefault => 104,
            Self::NumberOfStates => 74,
            Self::StateText => 110,
            Self::SystemStatus => 112,
            Self::VendorName => 121,
            Self::VendorIdentifier => 120,
            Self::ModelName => 70,
            Self::FirmwareRevision => 44,
            Self::ApplicationSoftwareVersion => 12,
            Self::ProtocolVersion => 98,
            Self::ProtocolRevision => 139,
            Self::ProtocolServicesSupported => 97,
            Self::ProtocolObjectTypesSupported => 96,
            Self::ObjectList => 76,
            Self::MaxApduLengthAccepted => 62,
            Self::SegmentationSupported => 107,
            Self::ApduTimeout => 11,
            Self::NumberOfApduRetries => 73,
            Self::MaxMaster => 64,
            Self::MaxInfoFrames => 63,
            Self::DatabaseRevision => 155,
            Self::All => 8,
            Self::Required => 105,
            Self::Optional => 80,
            Self::Unknown(v) => v,
        }
    }
}
